<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="microver">

    <xacro:include filename="constants.xacro" />
    <xacro:include filename="inertial_macros.xacro" />
    <xacro:include filename="gazebo_control.xacro" />

    <material name="black">
        <color rgba="0 0 0 1" />
    </material>
    <material name="white">
        <color rgba="1 1 1 1" />
    </material>
    <material name="blue">
        <color rgba="0.2 0.2 1 1" />
    </material>

    <material name="purple">
        <color rgba="0.62 0.12 0.94 1" />
    </material>



    <!-- the base link located in the middle of the line between the center of both back wheels -->
    <link name="base_link">
        <visual>
            <geometry>
                <cylinder length="0.003" radius="0.003"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name="white" />
        </visual>
    </link>


                    <!-- ####################### JOINTS ########################## -->


    <joint name="chassis_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="chassis" />
    </joint>

                                        <!-- WHEEL JOINTS -->

    <joint name="front_left_wheel_joint" type="continuous">
        <origin xyz="${LENGTH - LEG_LENGTH} ${((WIDTH/2) + LEG_WIDTH + (WHEEL_WIDTH/2))} ${WHEEL_RADIUS}" rpy="-${pi/2} 0 0" />
        <parent link="base_link" />
        <child link="front_left_wheel_link" />
        <axis xyz="0 0 1"/>
        <limit effort="100" velocity="100"/>
        <dynamics damping="0.1" friction="0.1"/>
    </joint>

    <joint name="front_right_wheel_joint" type="continuous">
        <origin xyz="${LENGTH - LEG_LENGTH} ${-((WIDTH/2) + LEG_WIDTH + (WHEEL_WIDTH/2))} ${WHEEL_RADIUS}" rpy="${pi/2} 0 0" />
        <parent link="base_link" />
        <child link="front_right_wheel_link" />
        <axis xyz="0 0 -1"/>
        <limit effort="100" velocity="100"/>
        <dynamics damping="0.1" friction="0.1"/>
    </joint>

    <joint name="back_left_wheel_joint" type="continuous">
        <origin xyz="0 ${((WIDTH/2) + LEG_WIDTH + (WHEEL_WIDTH/2))} ${WHEEL_RADIUS}" rpy="-${pi/2} 0 0" />
        <parent link="base_link" />
        <child link="back_left_wheel_link" />
        <axis xyz="0 0 1"/>
        <limit effort="100" velocity="100"/>
        <dynamics damping="0.1" friction="0.1"/>
    </joint>

    <joint name="back_right_wheel_joint" type="continuous">
        <origin xyz="0 ${-((WIDTH/2) + LEG_WIDTH + (WHEEL_WIDTH/2))} ${WHEEL_RADIUS}" rpy="${pi/2} 0 0" />
        <parent link="base_link" />
        <child link="back_right_wheel_link" />
        <axis xyz="0 0 -1"/>
        <limit effort="100" velocity="100"/>
        <dynamics damping="0.1" friction="0.1"/>
    </joint>

                                <!-- LEG JOINTS = FIXED -->


    <joint name="back_left_leg_joint" type="fixed">
        <origin xyz="0 ${((WIDTH/2)+(LEG_WIDTH/2))} ${LEG_HEIGHT/2 + WHEEL_RADIUS}" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="back_left_leg_link" />
    </joint>

    <joint name="back_right_leg_joint" type="fixed">
        <origin xyz="0 ${-((WIDTH/2)+(LEG_WIDTH/2))} ${LEG_HEIGHT/2 + WHEEL_RADIUS}" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="back_right_leg_link" />
    </joint>

    <joint name="front_left_leg_joint" type="fixed">
        <origin xyz="${LENGTH - LEG_LENGTH} ${((WIDTH/2)+(LEG_WIDTH/2))} ${LEG_HEIGHT/2 + WHEEL_RADIUS}" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="front_left_leg_link" />
    </joint>

    <joint name="front_right_leg_joint" type="fixed">
        <origin xyz="${LENGTH - LEG_LENGTH} ${-((WIDTH/2)+(LEG_WIDTH/2))} ${LEG_HEIGHT/2 + WHEEL_RADIUS}"
            rpy="0 0 0" />
        <parent link="base_link" />
        <child link="front_right_leg_link" />
    </joint>

                    <!-- ####################### LINKS ########################## -->


    <link name="chassis">
        <visual>
            <geometry>
                <box size="${LENGTH} ${WIDTH} ${HEIGHT}" />
            </geometry>
            <origin xyz="${LENGTH/2 - LEG_LENGTH/2} 0 ${LEG_HEIGHT - HEIGHT/2 + WHEEL_RADIUS}" rpy="0 0 0"/>
            <material name="black" />
        </visual>
        <collision>
            <geometry>
                <box size="${LENGTH} ${WIDTH} ${HEIGHT}" />
            </geometry>
            <origin xyz="${LENGTH/2 - LEG_LENGTH/2} 0 ${LEG_HEIGHT - HEIGHT/2 + WHEEL_RADIUS}" rpy="0 0 0"/>
        </collision>
        <xacro:inertial_box mass="${MASS}" x="${LENGTH}" y="${WIDTH}" z="${HEIGHT}">
            <origin xyz="${LENGTH/2 - LEG_LENGTH/2} 0 ${LEG_HEIGHT - HEIGHT/2 + WHEEL_RADIUS}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    

                                        <!-- LEG LINKS -->


    <!-- need to add inertias for the legs -->
    <link name="back_left_leg_link">
        <visual>
            <geometry>
                <box size="${LEG_LENGTH} ${LEG_WIDTH} ${LEG_HEIGHT}" />
            </geometry>
            <material name="black" />
        </visual>
        <collision>
            <geometry>
                <box size="${LEG_LENGTH} ${LEG_WIDTH} ${LEG_HEIGHT}" />
            </geometry>
        </collision>
        <xacro:inertial_box mass="${LEG_MASS}" x="${LEG_LENGTH}" y="${LEG_WIDTH}" z="${LEG_HEIGHT}">
            <origin xyz="0 0 0" />
        </xacro:inertial_box>
    </link>

    


    <link name="back_right_leg_link">
        <visual>
            <geometry>
                <box size="${LEG_LENGTH} ${LEG_WIDTH} ${LEG_HEIGHT}" />
            </geometry>
            <material name="black" />
        </visual>
        <collision>
            <geometry>
                <box size="${LEG_LENGTH} ${LEG_WIDTH} ${LEG_HEIGHT}" />
            </geometry>
        </collision>
        <xacro:inertial_box mass="${LEG_MASS}" x="${LEG_LENGTH}" y="${LEG_WIDTH}" z="${LEG_HEIGHT}">
            <origin xyz="0 0 0" />
        </xacro:inertial_box>
    </link>

    

    <link name="front_left_leg_link">
        <visual>
            <geometry>
                <box size="${LEG_LENGTH} ${LEG_WIDTH} ${LEG_HEIGHT}" />
            </geometry>
            <material name="black" />
        </visual>
        <collision>
            <geometry>
                <box size="${LEG_LENGTH} ${LEG_WIDTH} ${LEG_HEIGHT}" />
            </geometry>
        </collision>
        <xacro:inertial_box mass="${LEG_MASS}" x="${LEG_LENGTH}" y="${LEG_WIDTH}" z="${LEG_HEIGHT}">
            <origin xyz="0 0 0" />
        </xacro:inertial_box>
        
    </link>

    

    <link name="front_right_leg_link">
        <visual>
            <geometry>
                <box size="${LEG_LENGTH} ${LEG_WIDTH} ${LEG_HEIGHT}" />
            </geometry>
            <material name="black" />
        </visual>
        <collision>
            <geometry>
                <box size="${LEG_LENGTH} ${LEG_WIDTH} ${LEG_HEIGHT}" />
            </geometry>
        </collision>
        <xacro:inertial_box mass="${LEG_MASS}" x="${LEG_LENGTH}" y="${LEG_WIDTH}" z="${LEG_HEIGHT}">
            <origin xyz="0 0 0" />
        </xacro:inertial_box>
    </link>

    

                                        <!-- WHEEL LINKS -->


    <link name="front_left_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${WHEEL_RADIUS}" length="${WHEEL_WIDTH}" />
            </geometry>
            <material name="purple" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${WHEEL_RADIUS}" length="${WHEEL_WIDTH}" />
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${WHEEL_MASS}" length="${WHEEL_WIDTH}" radius="${WHEEL_RADIUS}">
            <origin xyz="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    

    <link name="front_right_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${WHEEL_RADIUS}" length="${WHEEL_WIDTH}" />
            </geometry>
            <material name="purple" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${WHEEL_RADIUS}" length="${WHEEL_WIDTH}" />
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${WHEEL_MASS}" length="${WHEEL_WIDTH}" radius="${WHEEL_RADIUS}">
            <origin xyz="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    

    <link name="back_left_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${WHEEL_RADIUS}" length="${WHEEL_WIDTH}" />
            </geometry>
            <material name="purple" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${WHEEL_RADIUS}" length="${WHEEL_WIDTH}" />
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${WHEEL_MASS}" length="${WHEEL_WIDTH}" radius="${WHEEL_RADIUS}">
            <origin xyz="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    

    <link name="back_right_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${WHEEL_RADIUS}" length="${WHEEL_WIDTH}" />
            </geometry>
            <material name="purple" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${WHEEL_RADIUS}" length="${WHEEL_WIDTH}" />
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${WHEEL_MASS}" length="${WHEEL_WIDTH}" radius="${WHEEL_RADIUS}">
            <origin xyz="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    


                                                <!-- Gazebo -->


    <gazebo reference="chassis">
        <material>Gazebo/Black</material>
    </gazebo>

    <gazebo reference="back_left_leg_link">
        <material>Gazebo/Black</material>
    </gazebo>

    <gazebo reference="back_right_leg_link">
        <material>Gazebo/Black</material>
    </gazebo>

    <gazebo reference="front_left_leg_link">
        <material>Gazebo/Black</material>
    </gazebo>

    <gazebo reference="front_right_leg_link">
        <material>Gazebo/Black</material>
    </gazebo>

    <gazebo reference="front_left_wheel_link">
        <material>Gazebo/Purple</material>
        <mu1 value="${MU1}" />
        <mu2 value="${MU2}" />
    </gazebo>

    <gazebo reference="front_right_wheel_link">
        <material>Gazebo/Purple</material>
        <mu1 value="${MU1}" />
        <mu2 value="${MU2}" />
    </gazebo>

    <gazebo reference="back_left_wheel_link">
        <material>Gazebo/Purple</material>
        <mu1 value="${MU1}" />
        <mu2 value="${MU2}" />
    </gazebo>

    <gazebo reference="back_right_wheel_link">
        <material>Gazebo/Purple</material>
        <mu1 value="${MU1}" />
        <mu2 value="${MU2}" />
    </gazebo>
    
</robot>